[project]
name = "oasis"
version = "0.1.0"
description = "OpenAlex S3 Ingest Service"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.40.45",
    "duckdb>=1.4.0",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "rich>=14.1.0",
]
